import { BotCodeResult, StrategyConfig } from '../types/trading';

/**
 * High-speed, instant client-side bot template compiler.
 * Generates battle-tested, production-ready trading scripts for Python (CCXT),
 * PineScript v5, Node.js/TypeScript, and MQL5 without any server latency.
 */
export function generateInstantBotCode(
  strategy: StrategyConfig,
  language: 'python_ccxt' | 'pinescript_v5' | 'nodejs_typescript' | 'mql5',
  symbol: string = 'BTC/USDT'
): BotCodeResult {
  const cleanSymbol = symbol.replace('/', '').toUpperCase();
  const baseSymbol = symbol.includes('/') ? symbol : `${symbol.slice(0, 3)}/${symbol.slice(3)}`;
  const params = (strategy.params || {}) as any;

  const fastEma = params.fastEma || 9;
  const slowEma = params.slowEma || 21;
  const rsiPeriod = params.rsiPeriod || 14;
  const rsiOb = params.rsiOverbought || 70;
  const rsiOs = params.rsiOversold || 30;
  const rrr = params.riskRewardRatio || 2.0;
  const leverage = params.leverage || 1;
  const riskPct = params.riskPerTradePercent || 1.5;
  const atrMult = params.atrMultiplierSL || 1.8;
  const useTrail = params.useTrailingStop !== false;

  if (language === 'python_ccxt') {
    const pyCode = [
      '"""',
      '================================================================================',
      `ALPHATRADER QUANTITATIVE EXECUTION BOT (PYTHON 3.10+ & ASYNC CCXT)`,
      `Strategy Name : ${strategy.name}`,
      `Category      : ${strategy.category}`,
      `Target Asset  : ${baseSymbol}`,
      `Architecture  : Non-blocking Async Event Loop + Dynamic ATR Risk Engine`,
      '================================================================================',
      '"""',
      '',
      'import asyncio',
      'import os',
      'import sys',
      'import time',
      'import logging',
      'from typing import Optional, Dict, Any',
      'import ccxt.async_support as ccxt',
      'import pandas as pd',
      'import numpy as np',
      'from dotenv import load_dotenv',
      '',
      'load_dotenv()',
      '',
      'logging.basicConfig(',
      '    level=logging.INFO,',
      '    format="%(asctime)s [%(levelname)s] (AlphaBot) %(message)s",',
      '    handlers=[',
      '        logging.StreamHandler(sys.stdout),',
      '        logging.FileHandler("bot_execution.log", mode="a", encoding="utf-8")',
      '    ]',
      ')',
      'logger = logging.getLogger("AlphaBot")',
      '',
      `SYMBOL = os.getenv("TRADING_SYMBOL", "${baseSymbol}")`,
      'TIMEFRAME = os.getenv("TIMEFRAME", "15m")',
      `LEVERAGE = int(os.getenv("LEVERAGE", "${leverage}"))`,
      `RISK_PER_TRADE_PCT = float(os.getenv("RISK_PER_TRADE_PCT", "${riskPct}"))`,
      'USE_TESTNET = os.getenv("USE_TESTNET", "true").lower() == "true"',
      '',
      'PARAMS = {',
      `    "strategy_id": "${strategy.id}",`,
      `    "fastEma": ${fastEma},`,
      `    "slowEma": ${slowEma},`,
      `    "rsiPeriod": ${rsiPeriod},`,
      `    "rsiOverbought": ${rsiOb},`,
      `    "rsiOversold": ${rsiOs},`,
      `    "riskRewardRatio": ${rrr},`,
      `    "atrMultiplier": ${atrMult},`,
      `    "useTrailingStop": ${useTrail ? 'True' : 'False'}`,
      '}',
      '',
      'class AlphaTradingEngine:',
      '    def __init__(self):',
      '        self.exchange: Optional[ccxt.binance] = None',
      '        self.position: Optional[Dict[str, Any]] = None',
      '        self.is_running = True',
      '        self.highest_price = 0.0',
      '',
      '    async def initialize(self):',
      '        api_key = os.getenv("BINANCE_API_KEY", "")',
      '        api_secret = os.getenv("BINANCE_API_SECRET", "")',
      '        self.exchange = ccxt.binance({',
      '            "apiKey": api_key,',
      '            "secret": api_secret,',
      '            "enableRateLimit": True,',
      '            "options": {',
      '                "defaultType": "future" if LEVERAGE > 1 else "spot",',
      '                "adjustForTimeDifference": True,',
      '            }',
      '        })',
      '        if USE_TESTNET:',
      '            self.exchange.set_sandbox_mode(True)',
      '            logger.info("[MODE] Running in TESTNET SANDBOX Mode (Zero Risk)")',
      '        else:',
      '            logger.warning("[MODE] RUNNING IN PRODUCTION LIVE CAPITAL MODE!")',
      '        await self.exchange.load_markets()',
      '        logger.info(f"Target Market: {SYMBOL} on {TIMEFRAME} Timeframe with {LEVERAGE}x Leverage")',
      '',
      '    async def fetch_market_state(self) -> pd.DataFrame:',
      '        ohlcv = await self.exchange.fetch_ohlcv(SYMBOL, timeframe=TIMEFRAME, limit=120)',
      '        df = pd.DataFrame(ohlcv, columns=["time", "open", "high", "low", "close", "volume"])',
      '        df["ema_fast"] = df["close"].ewm(span=PARAMS["fastEma"], adjust=False).mean()',
      '        df["ema_slow"] = df["close"].ewm(span=PARAMS["slowEma"], adjust=False).mean()',
      '        delta = df["close"].diff()',
      '        gain = (delta.where(delta > 0, 0)).rolling(window=PARAMS["rsiPeriod"]).mean()',
      '        loss = (-delta.where(delta < 0, 0)).rolling(window=PARAMS["rsiPeriod"]).mean()',
      '        rs = gain / (loss + 1e-10)',
      '        df["rsi"] = 100 - (100 / (1 + rs))',
      '        high_low = df["high"] - df["low"]',
      '        high_close = (df["high"] - df["close"].shift()).abs()',
      '        low_close = (df["low"] - df["close"].shift()).abs()',
      '        tr = pd.concat([high_low, high_close, low_close], axis=1).max(axis=1)',
      '        df["atr"] = tr.rolling(window=14).mean()',
      '        return df',
      '',
      '    def evaluate_signals(self, df: pd.DataFrame) -> str:',
      '        curr = df.iloc[-1]',
      '        prev = df.iloc[-2]',
      '        bullish_cross = (prev["ema_fast"] <= prev["ema_slow"]) and (curr["ema_fast"] > curr["ema_slow"])',
      '        bearish_cross = (prev["ema_fast"] >= prev["ema_slow"]) and (curr["ema_fast"] < curr["ema_slow"])',
      '        if (bullish_cross or curr["ema_fast"] > curr["ema_slow"]) and (curr["rsi"] < PARAMS["rsiOverbought"]) and (curr["rsi"] > 42):',
      '            return "BUY"',
      '        if bearish_cross or curr["rsi"] > PARAMS["rsiOverbought"]:',
      '            return "SELL"',
      '        return "HOLD"',
      '',
      '    async def execute_trade(self, side: str, price: float, atr: float):',
      '        balance = await self.exchange.fetch_balance()',
      '        free_usdt = balance["free"].get("USDT", 10000.0)',
      '        risk_capital = free_usdt * (RISK_PER_TRADE_PCT / 100.0)',
      '        stop_dist = atr * PARAMS["atrMultiplier"]',
      '        if stop_dist <= 0: stop_dist = price * 0.015',
      '        qty = (risk_capital * LEVERAGE) / stop_dist',
      '        max_cost = free_usdt * 0.90',
      '        if (qty * price) / LEVERAGE > max_cost: qty = (max_cost * LEVERAGE) / price',
      '        qty = self.exchange.amount_to_precision(SYMBOL, qty)',
      '        if float(qty) <= 0: return',
      '        tp_price = price + (stop_dist * PARAMS["riskRewardRatio"]) if side == "BUY" else price - (stop_dist * PARAMS["riskRewardRatio"])',
      '        sl_price = price - stop_dist if side == "BUY" else price + stop_dist',
      '        logger.info(f"[ORDER] {side} {qty} {SYMBOL} @ {price:.2f} | TP: {tp_price:.2f} | SL: {sl_price:.2f}")',
      '        try:',
      '            order = await self.exchange.create_order(symbol=SYMBOL, type="market", side=side.lower(), amount=float(qty))',
      '            self.position = {',
      '                "side": side, "entry_price": price, "amount": float(qty),',
      '                "stop_loss": sl_price, "take_profit": tp_price, "highest_price": price',
      '            }',
      '            logger.info(f"Order Executed ID: {order.get(\'id\', \'N/A\')}")',
      '        except Exception as e:',
      '            logger.error(f"Order Execution Failed: {e}")',
      '',
      '    async def manage_position(self, current_price: float, atr: float):',
      '        if not self.position: return',
      '        pos = self.position',
      '        if current_price > pos["highest_price"]:',
      '            pos["highest_price"] = current_price',
      '            if PARAMS["useTrailingStop"]:',
      '                new_sl = current_price - (atr * PARAMS["atrMultiplier"])',
      '                if new_sl > pos["stop_loss"]:',
      '                    pos["stop_loss"] = new_sl',
      '                    logger.info(f"[TRAILING STOP] Stop Loss updated to {new_sl:.2f}")',
      '        if current_price >= pos["take_profit"]:',
      '            await self.close_position(current_price, "Take Profit Hit")',
      '        elif current_price <= pos["stop_loss"]:',
      '            await self.close_position(current_price, "Stop Loss Hit")',
      '',
      '    async def close_position(self, price: float, reason: str):',
      '        if not self.position: return',
      '        amount = self.position["amount"]',
      '        logger.info(f"Closing position ({reason}) of {amount} {SYMBOL} @ {price:.2f}")',
      '        try:',
      '            await self.exchange.create_order(symbol=SYMBOL, type="market", side="sell", amount=amount)',
      '            pnl_pct = ((price - self.position["entry_price"]) / self.position["entry_price"]) * 100.0 * LEVERAGE',
      '            logger.info(f"Position Closed. Realized PnL: {pnl_pct:+.2f}%")',
      '        except Exception as e:',
      '            logger.error(f"Error while closing position: {e}")',
      '        finally:',
      '            self.position = None',
      '',
      '    async def run(self):',
      '        await self.initialize()',
      '        logger.info("Bot execution loop initialized. Press Ctrl+C to terminate.")',
      '        while self.is_running:',
      '            try:',
      '                df = await self.fetch_market_state()',
      '                current_price = df.iloc[-1]["close"]',
      '                current_atr = df.iloc[-1]["atr"]',
      '                if self.position:',
      '                    await self.manage_position(current_price, current_atr)',
      '                else:',
      '                    sig = self.evaluate_signals(df)',
      '                    if sig == "BUY":',
      '                        await self.execute_trade("BUY", current_price, current_atr)',
      '                await asyncio.sleep(10)',
      '            except Exception as e:',
      '                logger.error(f"Loop error: {e}")',
      '                await asyncio.sleep(5)',
      '',
      '    async def shutdown(self):',
      '        self.is_running = False',
      '        if self.exchange:',
      '            await self.exchange.close()',
      '        logger.info("Bot terminated safely.")',
      '',
      'if __name__ == "__main__":',
      '    bot = AlphaTradingEngine()',
      '    loop = asyncio.get_event_loop()',
      '    try:',
      '        loop.run_until_complete(bot.run())',
      '    except KeyboardInterrupt:',
      '        loop.run_until_complete(bot.shutdown())',
    ].join('\n');

    return {
      language: 'python_ccxt',
      filename: `${strategy.id}_bot.py`,
      code: pyCode,
      installationGuide: [
        '1. Pastikan Python 3.10+ terpasang: python --version',
        '2. Install library: pip install ccxt pandas numpy python-dotenv',
        '3. Buat file .env di direktori yang sama lalu isi BINANCE_API_KEY dan BINANCE_API_SECRET.',
        '4. Jalankan mode testnet terlebih dahulu (USE_TESTNET=true) untuk pengujian bebas risiko.',
        `5. Jalankan script: python ${strategy.id}_bot.py`,
      ],
      keyFeatures: [
        'Async Non-Blocking Event Loop via CCXT library dengan proteksi rate limit bursa',
        `Dynamic ATR Trailing Stop Loss & Risk Reward Ratio 1:${rrr}`,
        `Risk Management per-trade (maks ${riskPct}% equity) & slippage clamp`,
        'Dual-channel logging: live output terminal dan berkas audit bot_execution.log',
      ],
    };
  }

  if (language === 'pinescript_v5') {
    const pineCode = [
      '//@version=5',
      `strategy("${strategy.name} [AlphaTrader Engine]", overlay=true, initial_capital=10000, default_qty_type=strategy.percent_of_equity, default_qty_value=${riskPct * 5}, commission_type=strategy.commission.percent, commission_value=0.05, slippage=2)`,
      '',
      '// ======================== STRATEGY PARAMETERS ========================',
      'grp_strat = "Strategy Logic Configuration"',
      `fastLen   = input.int(${fastEma}, "Fast EMA Period", minval=1, group=grp_strat)`,
      `slowLen   = input.int(${slowEma}, "Slow EMA Period", minval=1, group=grp_strat)`,
      `rsiLen    = input.int(${rsiPeriod}, "RSI Smoothing Period", minval=1, group=grp_strat)`,
      `rsiOb     = input.int(${rsiOb}, "RSI Overbought Barrier", minval=50, maxval=95, group=grp_strat)`,
      `rsiOs     = input.int(${rsiOs}, "RSI Oversold Barrier", minval=5, maxval=50, group=grp_strat)`,
      '',
      'grp_risk  = "Risk & Position Sizing"',
      'atrLen    = input.int(14, "ATR Lookback Period", group=grp_risk)',
      `atrMult   = input.float(${atrMult}, "ATR Stop Loss Multiplier", step=0.1, group=grp_risk)`,
      `rrr       = input.float(${rrr}, "Risk to Reward Ratio (RRR)", step=0.1, group=grp_risk)`,
      `useTrail  = input.bool(${useTrail}, "Enable Dynamic ATR Trailing Stop", group=grp_risk)`,
      '',
      '// ======================== INDICATOR CALCULATIONS ========================',
      'fastEma = ta.ema(close, fastLen)',
      'slowEma = ta.ema(close, slowLen)',
      'rsiVal  = ta.rsi(close, rsiLen)',
      'atrVal  = ta.atr(atrLen)',
      '',
      '// Entry Conditions',
      'bullishSignal = ta.crossover(fastEma, slowEma) and rsiVal < rsiOb and rsiVal > 40',
      'bearishSignal = ta.crossunder(fastEma, slowEma) or rsiVal > rsiOb',
      '',
      '// Position Tracking Variables',
      'var float entryPrice = na',
      'var float stopLossPrice = na',
      'var float takeProfitPrice = na',
      '',
      '// ======================== STRATEGY EXECUTION ========================',
      'if (bullishSignal and strategy.position_size == 0)',
      '    stopDist = atrVal * atrMult',
      '    entryPrice := close',
      '    stopLossPrice := close - stopDist',
      '    takeProfitPrice := close + (stopDist * rrr)',
      '    strategy.entry("Long Alpha", strategy.long, comment="Alpha Buy")',
      '    strategy.exit("Bracket Exit", "Long Alpha", stop=stopLossPrice, limit=takeProfitPrice, comment_loss="SL Hit", comment_profit="TP Hit")',
      '',
      '// Trailing Stop Logic',
      'if (useTrail and strategy.position_size > 0)',
      '    trailSL = close - (atrVal * atrMult)',
      '    if (trailSL > stopLossPrice)',
      '        stopLossPrice := trailSL',
      '        strategy.exit("Bracket Exit", "Long Alpha", stop=stopLossPrice, limit=takeProfitPrice, comment_loss="Trail SL")',
      '',
      'if (bearishSignal and strategy.position_size > 0)',
      '    strategy.close("Long Alpha", comment="Exit Signal")',
      '',
      '// ======================== VISUAL OVERLAYS ========================',
      'plot(fastEma, "Fast EMA", color=color.new(#3B82F6, 0), linewidth=2)',
      'plot(slowEma, "Slow EMA", color=color.new(#F59E0B, 0), linewidth=2)',
      '',
      'plotshape(bullishSignal and strategy.position_size == 0, title="Buy Alert", style=shape.triangleup, location=location.belowbar, color=color.new(#10B981, 0), size=size.small, text="ALPHA BUY")',
      'plotshape(bearishSignal and strategy.position_size > 0, title="Exit Alert", style=shape.triangledown, location=location.abovebar, color=color.new(#EF4444, 0), size=size.small, text="EXIT")',
      '',
      'plot(strategy.position_size > 0 ? stopLossPrice : na, "Dynamic Stop Loss", color=color.new(#EF4444, 20), style=plot.style_linebr, linewidth=2)',
      'plot(strategy.position_size > 0 ? takeProfitPrice : na, "Take Profit Target", color=color.new(#10B981, 20), style=plot.style_linebr, linewidth=2)',
    ].join('\n');

    return {
      language: 'pinescript_v5',
      filename: `${strategy.id}_strategy.pine`,
      code: pineCode,
      installationGuide: [
        `1. Buka TradingView.com dan pilih chart ${baseSymbol}.`,
        '2. Klik tab "Pine Editor" pada bar bagian bawah.',
        '3. Hapus kode default, tempelkan script di atas, lalu klik "Save" dan "Add to chart".',
        '4. Buka tab "Strategy Tester" untuk melihat audit kalkulasi net profit, win rate, dan drawdown secara instan.',
      ],
      keyFeatures: [
        'Pine Script version=5 standar industri kompatibel penuh dengan TradingView',
        'Visualisasi bracket order (Garis hijau Take Profit & Garis merah Stop Loss)',
        'Built-in slippage model dan estimasi biaya transaksi bursa (commission=0.05%)',
      ],
    };
  }

  if (language === 'nodejs_typescript') {
    const tsCode = [
      "import WebSocket from 'ws';",
      "import dotenv from 'dotenv';",
      '',
      'dotenv.config();',
      '',
      `const SYMBOL = process.env.SYMBOL || '${cleanSymbol}';`,
      `const FAST_EMA_LEN = ${fastEma};`,
      `const SLOW_EMA_LEN = ${slowEma};`,
      `const RSI_LEN = ${rsiPeriod};`,
      `const RRR = ${rrr};`,
      `const ATR_MULT = ${atrMult};`,
      '',
      'class AlphaWebSocketBot {',
      '  private ws!: WebSocket;',
      '  private prices: number[] = [];',
      '  private inPosition = false;',
      '  private entryPrice = 0;',
      '  private stopLoss = 0;',
      '  private takeProfit = 0;',
      '',
      '  public start() {',
      '    console.log(`[AlphaBot] Starting WebSocket live feed for ${SYMBOL}...`);',
      '    this.ws = new WebSocket(`wss://stream.binance.com:9443/ws/${SYMBOL.toLowerCase()}@kline_15m`);',
      '',
      '    this.ws.on("open", () => {',
      '      console.log("Connected to Binance WebSocket Stream.");',
      '    });',
      '',
      '    this.ws.on("message", (data: string) => {',
      '      try {',
      '        const payload = JSON.parse(data);',
      '        const kline = payload.k;',
      '        if (kline && kline.x) {',
      '          const closePrice = parseFloat(kline.c);',
      '          this.onCandleClose(closePrice);',
      '        }',
      '      } catch (err) {',
      '        console.error("Error processing stream payload:", err);',
      '      }',
      '    });',
      '',
      '    this.ws.on("close", () => {',
      '      console.warn("WebSocket disconnected. Reconnecting in 3 seconds...");',
      '      setTimeout(() => this.start(), 3000);',
      '    });',
      '  }',
      '',
      '  private onCandleClose(price: number) {',
      '    this.prices.push(price);',
      '    if (this.prices.length > 100) this.prices.shift();',
      '',
      '    if (this.prices.length < SLOW_EMA_LEN + 2) {',
      '      console.log(`[Warmup] Collecting bars: ${this.prices.length}/${SLOW_EMA_LEN + 2}`);',
      '      return;',
      '    }',
      '',
      '    const fastEma = this.calculateEMA(this.prices, FAST_EMA_LEN);',
      '    const slowEma = this.calculateEMA(this.prices, SLOW_EMA_LEN);',
      '    const rsi = this.calculateRSI(this.prices, RSI_LEN);',
      '',
      '    console.log(`Bar Close: $${price.toFixed(2)} | Fast EMA: $${fastEma.toFixed(2)} | Slow EMA: $${slowEma.toFixed(2)} | RSI: ${rsi.toFixed(1)}`);',
      '',
      '    if (this.inPosition) {',
      '      if (price >= this.takeProfit) {',
      '        this.closePosition(price, "TAKE PROFIT HIT");',
      '      } else if (price <= this.stopLoss) {',
      '        this.closePosition(price, "STOP LOSS HIT");',
      '      } else if (fastEma < slowEma) {',
      '        this.closePosition(price, "MOMENTUM REVERSAL CROSS");',
      '      }',
      '    } else {',
      `      if (fastEma > slowEma && rsi < ${rsiOb} && rsi > 40) {`,
      '        this.openPosition(price);',
      '      }',
      '    }',
      '  }',
      '',
      '  private openPosition(price: number) {',
      '    this.inPosition = true;',
      '    this.entryPrice = price;',
      '    const estStopDist = price * 0.012 * ATR_MULT;',
      '    this.stopLoss = price - estStopDist;',
      '    this.takeProfit = price + (estStopDist * RRR);',
      '    console.log(`[BUY ORDER] Entered Long @ $${price.toFixed(2)} | TP: $${this.takeProfit.toFixed(2)} | SL: $${this.stopLoss.toFixed(2)}`);',
      '  }',
      '',
      '  private closePosition(price: number, reason: string) {',
      '    const pnlPct = ((price - this.entryPrice) / this.entryPrice) * 100;',
      '    console.log(`[SELL ORDER] Position closed (${reason}) @ $${price.toFixed(2)} | Net PnL: ${pnlPct.toFixed(2)}%`);',
      '    this.inPosition = false;',
      '  }',
      '',
      '  private calculateEMA(data: number[], period: number): number {',
      '    const k = 2 / (period + 1);',
      '    let ema = data[0];',
      '    for (let i = 1; i < data.length; i++) {',
      '      ema = data[i] * k + ema * (1 - k);',
      '    }',
      '    return ema;',
      '  }',
      '',
      '  private calculateRSI(data: number[], period: number): number {',
      '    let gains = 0;',
      '    let losses = 0;',
      '    for (let i = data.length - period; i < data.length; i++) {',
      '      const diff = data[i] - data[i - 1];',
      '      if (diff >= 0) gains += diff;',
      '      else losses -= diff;',
      '    }',
      '    const rs = (gains / period) / ((losses / period) || 1);',
      '    return 100 - (100 / (1 + rs));',
      '  }',
      '}',
      '',
      'const bot = new AlphaWebSocketBot();',
      'bot.start();',
    ].join('\n');

    return {
      language: 'nodejs_typescript',
      filename: `${strategy.id}_bot.ts`,
      code: tsCode,
      installationGuide: [
        '1. Install dependencies: npm install ws dotenv @types/ws tsx',
        `2. Jalankan bot secara instan: npx tsx ${strategy.id}_bot.ts`,
      ],
      keyFeatures: [
        'Ultra-low latency Binance WebSocket stream receiver',
        'Built-in automatic reconnection engine',
        'Zero bloated dependency footprint',
      ],
    };
  }

  // MQL5 (MT5 EA)
  const mqlCode = [
    '//+------------------------------------------------------------------+',
    `//|                                              ${strategy.id}_EA.mq5 |`,
    '//|                                  Copyright 2026, AlphaTrader AI  |',
    '//+------------------------------------------------------------------+',
    '#property copyright "AlphaTrader Quant"',
    '#property link      "https://alphatrader.quant"',
    '#property version   "3.00"',
    '#property strict',
    '',
    '#include <Trade\\Trade.mqh>',
    'CTrade trade;',
    '',
    `input int    InpFastEMA   = ${fastEma};       // Fast EMA Period`,
    `input int    InpSlowEMA   = ${slowEma};      // Slow EMA Period`,
    `input int    InpRSIPeriod = ${rsiPeriod};    // RSI Period`,
    `input double InpRiskPct   = ${riskPct};      // Risk Per Trade (%)`,
    `input double InpRRR       = ${rrr};          // Risk Reward Ratio`,
    `input double InpATRMult   = ${atrMult};      // ATR Stop Loss Multiplier`,
    '',
    'int handle_fast_ema;',
    'int handle_slow_ema;',
    'int handle_rsi;',
    'int handle_atr;',
    '',
    'int OnInit()',
    '{',
    '   handle_fast_ema = iMA(_Symbol, _Period, InpFastEMA, 0, MODE_EMA, PRICE_CLOSE);',
    '   handle_slow_ema = iMA(_Symbol, _Period, InpSlowEMA, 0, MODE_EMA, PRICE_CLOSE);',
    '   handle_rsi      = iRSI(_Symbol, _Period, InpRSIPeriod, PRICE_CLOSE);',
    '   handle_atr      = iATR(_Symbol, _Period, 14);',
    '   if(handle_fast_ema == INVALID_HANDLE || handle_slow_ema == INVALID_HANDLE) {',
    '      Print("Error creating indicator handles");',
    '      return INIT_FAILED;',
    '   }',
    '   trade.SetExpertMagicNumber(998877);',
    '   return(INIT_SUCCEEDED);',
    '}',
    '',
    'void OnDeinit(const int reason)',
    '{',
    '   IndicatorRelease(handle_fast_ema);',
    '   IndicatorRelease(handle_slow_ema);',
    '   IndicatorRelease(handle_rsi);',
    '   IndicatorRelease(handle_atr);',
    '}',
    '',
    'void OnTick()',
    '{',
    '   if(!IsNewBar()) return;',
    '   double fast[2], slow[2], rsi[2], atr[1];',
    '   CopyBuffer(handle_fast_ema, 0, 1, 2, fast);',
    '   CopyBuffer(handle_slow_ema, 0, 1, 2, slow);',
    '   CopyBuffer(handle_rsi, 0, 1, 2, rsi);',
    '   CopyBuffer(handle_atr, 0, 1, 1, atr);',
    `   bool buySignal = (fast[0] <= slow[0] && fast[1] > slow[1]) && rsi[1] < ${rsiOb};`,
    '   bool sellSignal = (fast[0] >= slow[0] && fast[1] < slow[1]);',
    '   if(PositionsTotal() == 0 && buySignal)',
    '   {',
    '      double ask = SymbolInfoDouble(_Symbol, SYMBOL_ASK);',
    '      double sl_distance = atr[0] * InpATRMult;',
    '      double sl = ask - sl_distance;',
    '      double tp = ask + (sl_distance * InpRRR);',
    '      double lot = 0.1;',
    '      trade.Buy(lot, _Symbol, ask, sl, tp, "AlphaTrader Long");',
    '   }',
    '}',
    '',
    'bool IsNewBar()',
    '{',
    '   static datetime last_time = 0;',
    '   datetime current_time = iTime(_Symbol, _Period, 0);',
    '   if(current_time != last_time)',
    '   {',
    '      last_time = current_time;',
    '      return true;',
    '   }',
    '   return false;',
    '}',
  ].join('\n');

  return {
    language: 'mql5',
    filename: `${strategy.id}_EA.mq5`,
    code: mqlCode,
    installationGuide: [
      '1. Buka MetaTrader 5 (MT5).',
      '2. Tekan F4 untuk membuka MetaEditor.',
      '3. Buat file baru (Expert Advisor) lalu tempelkan seluruh kode di atas.',
      '4. Tekan F7 untuk compile dan drag EA ke chart instrumen Anda.',
    ],
    keyFeatures: [
      'Kompatibel penuh dengan platform MetaTrader 5 (MT5)',
      'Eksekusi CTrade dengan Magic Number isolation',
      'Kalkulasi bar-by-bar bebas repainting',
    ],
  };
}
